# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specifies npm as the dependency manager
    directory: "/"           # Location of the `package.json` file (root directory)
    schedule:
      interval: "weekly"     # Checks for updates weekly
    commit-message:
      prefix: "chore: "      # Custom commit message prefix for Dependabot PRs
    open-pull-requests-limit: 5 # Limits the number of active PRs
    labels:
      - "dependencies"
